apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: auto-builder-ms
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    unhealthyThreshold: 3
    healthyThreshold: 2
    type: HTTP
    requestPath: /health-check