apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-builder-ms
data:
  nginx.conf: |
    events {}
    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=30s;
      server {
        listen 80;

        location / {
          return 200;
        }
        
        location ^~ /auto-builder {
            rewrite ^/auto-builder(/?)(.*)$ /$2 break;
            proxy_pass http://auto-builder-ms;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rewrite-auto-builder-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rewrite-auto-builder-ms
  template:
    metadata:
      labels:
        app: rewrite-auto-builder-ms
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: auto-builder-ms
---
apiVersion: v1
kind: Service
metadata:
  name: rewrite-auto-builder-ms
spec:
  selector:
    app: rewrite-auto-builder-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer