apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: auto-builder-ms
  namespace: tpl
spec:
  timeoutSec: 120
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    unhealthyThreshold: 3
    healthyThreshold: 2
    type: HTTP
    requestPath: /
---
apiVersion: v1
kind: Service
metadata:
  name: auto-builder-ms
  namespace: tpl
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"auto-builder-ms"}}'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: auto-builder-ms