apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deployment-name>
  namespace: <namespace-name>
  labels:
    username: <username-label>
    website: <website-label>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <deployment-name>
  template:
    metadata:
      labels:
        app: <deployment-name>
    spec:
      containers:
      - name: <deployment-name>
        image: <image-name>
        ports:
        - containerPort: <port-number>
        env:         
<environment-variables>