apiVersion: v1
kind: ConfigMap
metadata:
  name: <configmap-name>
data:
  nginx.conf: |
    events {}
    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=30s;
      server {
        listen 80;

        location / {
          return 200;
        }
        
        location ^~ <config-path> {
            rewrite ^<config-path>(/?)(.*)$ /$2 break;
            proxy_pass http://<service-name>;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deploy-name>-rewrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <deploy-name>-rewrite
  template:
    metadata:
      labels:
        app: <deploy-name>-rewrite
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: <configmap-name>
---
apiVersion: v1
kind: Service
metadata:
  name: <deploy-name>-rewrite-service
spec:
  selector:
    app: <deploy-name>-rewrite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: <service-type>