apiVersion: v1
kind: ConfigMap
metadata:
  name: <configmap-name>
  namespace: <namespace-name>
  labels:
    username: <username-label>
data:
  nginx.conf: |
    events {}
    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=30s;
      server {
        listen 80;

        location / {
          return 200;
        }
        
<rewrite-locations>
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <rewrite-deploy-name>
  namespace: <namespace-name>
  labels:
    username: <username-label>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <rewrite-deploy-name>
  template:
    metadata:
      labels:
        app: <rewrite-deploy-name>
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: <configmap-name>
---
apiVersion: v1
kind: Service
metadata:
  name: <rewrite-service-name>
  namespace: <namespace-name>
  labels:
    username: <username-label>
spec:
  selector:
    app: <rewrite-deploy-name>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: <service-type>